### PR TITLE
moved cards to new array on click

### PR DESCRIPTION
**Pull request by tylerjhevia**
Moved cards to selected array on click and displayed selected cards above regular DistrictContainer

### CODE REVIEW

**Comment by jackmallahan** [comment]
That is great, have you added styling to those new cards yet?

**Comment by tylerjhevia** [comment]
Not yet, we still need to add outlines to selected cards and work on transitions

**Comment by jackmallahan** [comment]
Cool. Should we style the cards first, or add functionality for removing cards from the selected array?

**Comment by tylerjhevia** [comment]
We should probably add the remove functionality first I think

**Comment by jackmallahan** [comment]
Perfect. I'll hop on that issue now

**Pull request merged**
